version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "dockerize -wait tcp://mysql:3306 -timeout 60s &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env  
    volumes:
      - .:/app
      - /app/__pycache__/
      - ./static:/app/static
      - ./media:/app/media
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    depends_on:
      - mysql
      - redis
      - celery

  mysql:
    image: mysql:8.0
    env_file:
      - .env 
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "dockerize -wait tcp://redis:6379 -timeout 60s &&
      celery -A StudentManagerProject worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  mysql_data: