services:
  django:
    command: ["sh", "-c", "dockerize -wait tcp://mysql:3306 -timeout 60s && python manage.py runserver 0.0.0.0:8000"]
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    depends_on:
      - mysql
      - redis
      - celery

  mysql:
    image: mysql:8.0
    env_file:
      - .env 
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A StudentManagerProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

